# sample file for setup for test environment setup
# We have one esxi host
esxi-hosts:
    - esxi:    1
      name:   "esxi-host1"
      host:   "192.168.200.50"
      password:   "rootpassword"
      username:   "root"
      port:   22
      nsxdp-cli:
        # here we have list command that we want to executed before we start testing.
        # in this case we allocate lcore per each vNIC before test starts.
        - cmd: "nsxdp-cli ens port migrate -p 2 -l 1 -d 0;nsxdp-cli ens port migrate -p 2 -l 1 -d 1"
        - cmd: "nsxdp-cli ens port migrate -p 3 -l 1 -d 0;nsxdp-cli ens port migrate -p 3 -l 1 -d 1"
        - cmd: "nsxdp-cli ens port migrate -p 4 -l 2 -d 0;nsxdp-cli ens port migrate -p 4 -l 2 -d 1"
        - cmd: "nsxdp-cli ens port migrate -p 5 -l 2 -d 0;nsxdp-cli ens port migrate -p 5 -l 2 -d 1"

# here object under a test.
# in this case we connect to a host run a command to start DPDK l3fwd as root via sudo.
# forward-stop and forward-start indicate script we need use to start the environment and stop the environment
dpkd-hosts:
    - dpdk:     1
      name:   "dpdk-vm1"
      host:   "192.168.200.59"
      password:   "VMware1!"
      username:   "dpdk"
      port:   22
      forward-stop: "echo 'VMware1!' | sudo -S kill $(ps aux | grep 'l3fwd' | awk '{print $2}')"
      forward-start: "echo 'VMware1!' | sudo -S nohup /home/dpdk/startL3fwd-4port-40G.sh >> /tmp/test.log 2>>/tmp/test.log"