#   global configuration setting for trex automation.
#   here we define a path to each respected scenario.
#   each scenario file might have N number of scenarios and each scenario might have different flow definition.
tester:
    - test:     1
      name:     "my first 70 byte test"
      test-scenario:   "scenarios/2lcore/100flow-vm-vm-2lcore-70byte.yaml"
      test-environment: "scenarios/5.2.1/environment-l2core.yaml"

    - test:     2
      name:     "my second 128 byte test"
      test-scenario:   "scenarios/2lcore/100flow-vm-vm-2lcore-128byte.yaml"
      test-environment: "scenarios/2lcore/environment-l2core.yaml"

